### ISSUE TITLE
[dev] Hard crash when goal rule is missing

### ISSUE THREAD

**Issue by mhhollomon** [mhhollomon/yalr#29]
Looks like the location is missing. In particular, the source is null, so dereferencing when printing crashes with SIGSEGV.

**Comment by mhhollomon** [comment]
Sample backtrace:
(gdb) bt
#0  yalr::text_source::analyze_lines (this=0x0) at /home/mhh/src/yalr/src/lib/sourcetext.cpp:56
#1  0x00005555555cc39f in yalr::text_source::offset_line_info (this=0x0, offset=0) at /home/mhh/src/yalr/src/lib/sourcetext.cpp:6
#2  0x00005555555cd1b1 in yalr::text_location::line_info (this=0x55555562f3e0) at /home/mhh/src/yalr/src/include/sourcetext.hpp:97
#3  0x00005555555ccf31 in yalr::error_info::output (this=0x55555562f3b0, strm=...) at /home/mhh/src/yalr/src/lib/errorinfo.cpp:7
